### ISSUE TITLE
MLX90640 and Home Assistant, not refreshing sensor values

### ISSUE THREAD

**Issue by thehijacker** [TheRealWaldo/thermal#131]
## Version of the custom_component

Latest version installed using HACS

## Configuration

```yaml

camera:
  - platform: thermal_vision
    name: Thermal Kabinet Camera
    host: http://10.0.107.25
    sensor:
      rows: 24
      cols: 32
    interpolate:
      method: disabled

sensor:
  - platform: thermal_vision
    name: Thermal Kabinet Sensor
    host: http://10.0.107.25
    sensor:
      rows: 24
      cols: 32

binary_sensor:
  - platform: thermal_vision
    name: Thermal Kabinet Occupancy
    host: http://10.0.107.25
```

## Describe the bug

I am trying to implement this inside the HA. Using the Pimoroni MLX90640 and ESP32 and this project:

https://github.com/pixelsquared/thermal_vision-ESP32-MLX90640

Camera is working. But with very low fps. By my guess with only 1fps. It is also rotate by 90 degrees.

Binary sensor is most of the time true. Even if I leave the room. Also the sensor values newer changes. I tried to set scan_interval to 5 seconds but again I do not get any values only, the first one on HA start.

![image](https://user-images.githubusercontent.com/13857043/156876752-8e9ee3cf-baf6-4903-b143-a05f858ff866.png)

How to debug this? My goal is to have reliable room presence detection.

Thank you.
